-- 코드를 입력하세요
SELECT B.TITLE as `TITLE`, B.BOARD_ID as `BOARD_ID`, R.REPLY_ID as `REPLY_ID`, R.WRITER_ID as `WRITER_ID`, R.CONTENTS as `CONTENTS`, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') as `CREATED_DATE`
FROM USED_GOODS_BOARD as B
INNER JOIN USED_GOODS_REPLY as R On B.BOARD_ID = R.BOARD_ID 
WHERE DATE_FORMAT(B.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC;